[feat] 주문 프로세스 개발
f-lab-edu/joy-mall pull request #50
Opened 2024-04-25 11:46 UTC by pak0426

- 주문 프로세스 개발을 위한 엔티티들 수정 및 Repository 생성
- 주문 로직 개발

[질문]
- OrderService에 createOrder() 메서드로 주문 로직을 구현해놨는데

SpringDataJDBC에서는 one-to-many만 지원합니다.
하지만 OrderItem과 ProductOption는 Many to One 관계여서 OrderItem안에 ProductOption을 가지고 있을 수 없습니다.

그래서 코드가 길어지게 됐는데 다른 방법이 있는지 궁금합니다.

2024-04-25 15:52 UTC, f-lab-odee requested changes

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/order/domain/entity/Order.java
> +    public Set<OrderItem> addOrderItem(OrderItem orderItem) {
orderItem이 나중에 추가될 일이 없을거같은데 add하는 함수가 필요할까요?
외부에서 컬렉션에 값을 수정하지 못하도록 초기 생성자에 만들면 어떨까요?

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/order/domain/entity/Order.java
> +    private LocalDateTime updatedDate;
지금 주문 상태가 여러개가 존재하고, 주문 프로세스상 최초 주문 진입, 결제,배송 등 여러번 상태가 변경될 수 있습니다.
이런 상태 변경을 updatedDate로만 관리하면 운영중에 들어오는 문의사항을 제대로 확인할 수 있을까요?
예를들어 고객이 결제를 했는데 배송이 안온다고 합니다. 주문에 대한 상세히스토리를 보고 고객 대응을 하려고 하는데 업데이트 시간밖에 없다면 확인하기가 어렵겠죠 . 
주문 상태변경을 추적관리할 수 있는 주문 히스토리를 관리해보세요

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/order/domain/entity/OrderItem.java
>      private Double pricePerItem;
가격이 Double일 필요가 있을까요?

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/product/domain/entity/ProductOption.java
> +    public void decreaseStock(Integer selectedQuantity) {
여러 사용자가 동시에 해당 물품을 사면 어떻게 될까요?
지금 동시성 제어가 되고있지 않아 재고관리가 제대로 처리안될거에요, 어떻게 동시성관리를 할지 고민해보시죠

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/order/service/OrderService.java
> +        for (CreateOrderItemRequest createOrderItems : createOrderRequests.getOrderItems()) {
지금 요 코드를 보면 getter를 너무 많이 사용하고 있는데요, 저희 getter/setter를 지양해야하는 이유는 많이 얘기했으니 아실거라 생각합니다!

```java
val order = requests.toCreateOrder();
val product = productRepository.findById(request.getProductId());
product.decreaseStock(order);
productRepository.save(product);
orderRepository.save(order);
```

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/order/service/OrderService.java
> +        for (CreateOrderItemRequest createOrderItems : createOrderRequests.getOrderItems()) {
order와  product 내부에 이미 option과 item을 들고있으니 도메인 내부에서 비지니스 로직을 처리해보시죠

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/customer/domain/entity/Address.java
>  public class Address {
Address보단 고객등록 주소를 나타내는 구체적인 네이밍을 사용해보면 좋을거같아요

address는 지역을 나타내는 아래정보로 vo를 만들는게 더 맞아보이네요
private String region;
private String city;
private String town;
private String street;
private String zipCode;

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/product/domain/repository/ProductRepository.java
> +    @Query(value = """
이 쿼리는 실무에서 사용하기에는 어려워 보이네요
우선 저번에 말씀드린것처럼 review 평점을 실시간으로 계산하게되면 리뷰량이 많을때 DB 부하가 너무 심해집니다.
리뷰가 작성될때 실시간으로 갱신하면서 관리하는게 좋아보여요.
추가로 productOption 서브쿼리에서 group by로 최소가격으로 조회하는 이유가 있나요?

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/product/service/CategoryService.java
> +                        buildCategoryChildren(category.getId())
요고 저번에 리뷰 남겼었는데 추가 코멘트가 반영안되었네요.
요부분 저라면 조회 로직과 변환로직을 분리해서 만들거같아요. 지금 조회와 동시에 변환을 하고 계신데요 카테고리를 다 조회한 후 dto로 변환해보세요

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/review/dto/ReviewStatDTO.java
> +    public double calculateAverageReviewRating() {
저번에 남겼던 리뷰인데요, 한 상품의 리뷰가 많으면 요런 부분은 부하가 발생하고 메모리 부족현상이 발생합니다

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/resources/application.yml
> +#  sql:
지금 프로파일이 local과 test 환경분리가 되어있지 않은데요, 환경분리를 해보세요
그리고 test 환경에서는 init:mode always로 운영하는게 좋습니다. 
요 부분 한번 생각해보시죠

2024-04-25 15:52 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/product/service/ProductService.java
>          List<Product> products = productRepository.findAll();
요부분도 전에 남겨두었는데요, findAll은 사용하지 마세요!

2024-04-26 05:46 UTC, pak0426 commented on src/main/java/com/mini/joymall/order/domain/entity/Order.java
> +    public Set<OrderItem> addOrderItem(OrderItem orderItem) {
넵 알겠습니다! 수정하겠습니다!

2024-04-26 05:57 UTC, pak0426 commented on src/main/java/com/mini/joymall/order/domain/entity/OrderItem.java
>      private Double pricePerItem;
초기 설계할때 할인율이나 쿠폰 적용을 생각해서 Double로 적용했던건데 소수점은 반올림처리를 가정하고 타입을 변경하겠습니다!

2024-04-26 06:01 UTC, pak0426 commented on src/main/java/com/mini/joymall/order/service/OrderService.java
> +        for (CreateOrderItemRequest createOrderItems : createOrderRequests.getOrderItems()) {
넵 알겠습니다 수정하겠습니다!!

2024-04-26 06:04 UTC, pak0426 commented on src/main/java/com/mini/joymall/product/domain/repository/ProductRepository.java
> +    @Query(value = """
>리뷰가 작성될때 실시간으로 갱신하면서 관리하는게 좋아보여요.

리팩토링하도록 하겠습니다!

>추가로 productOption 서브쿼리에서 group by로 최소가격으로 조회하는 이유가 있나요?

상품 리스트를 보여줄때 가격도 제공해야 하는데 상품 옵션 중 가장 낮은 가격을 리스트에 함께 보여주는게 좋을거 같다고 생각했습니다.

2024-04-26 06:05 UTC, pak0426 commented on src/main/java/com/mini/joymall/customer/domain/entity/Address.java
>  public class Address {
넵 알겠습니다!

2024-04-26 06:07 UTC, pak0426 commented on src/main/java/com/mini/joymall/product/service/CategoryService.java
> +                        buildCategoryChildren(category.getId())
네 알겠습니다 수정하겠습니다!

2024-04-26 06:09 UTC, pak0426 commented on src/main/java/com/mini/joymall/review/dto/ReviewStatDTO.java
> +    public double calculateAverageReviewRating() {
실시간으로 계산해주는게 아닌 갱신으로 리팩토링하겠습니다!

2024-04-30 08:40 UTC, pak0426 reviewed
id를 주입하는

2024-04-30 08:49 UTC, pak0426 commented
[[refactor] 모든 findAll() 지우기](https://github.com/f-lab-edu/joy-mall/pull/50/commits/30bfc85315dde8049d41bf375d348878d08e698f)
[[refactor] 가격 Double 에서 Integer 로 변경](https://github.com/f-lab-edu/joy-mall/pull/50/commits/588dd7916c9294837c57b2db0c7b7020dd7c8be7)
[[refactor] Address 를 구체적인 이름 변경 임베디드 Location 클래스 생성](https://github.com/f-lab-edu/joy-mall/pull/50/commits/0430c9e2adccf48d083f91a0429e8e0feca143e7)

위 커밋들은 이번 PR 코멘트 남겨주신 부분들 처리한 커밋입니다.

2024-04-30 17:46 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/product/domain/entity/ProductOption.java
> +    private Integer price;
박싱된 타입을 쓸 필요가 있을까요? 
이펙티브 자바 item 61을 찾아보시면 박싱된 타입과 기본타입을 써야할때에 대한 설명이 잘 나와있습니다
참고해보세요!

2024-05-01 11:33 UTC, pak0426 commented on src/main/java/com/mini/joymall/product/domain/entity/ProductOption.java
> +    private Integer price;
알겠습니다!

2024-05-08 15:39 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/product/domain/repository/ProductRepository.java
> +    @Modifying
해당 부분도 업데이트 쿼리로 작성되어있네요.
spring data jdbc를 사용할때는 update 쿼리를 직접 작성하지 말고 save를 이용해보세요
추가로 요 부분도 역시 동시성 이슈가 발생합니다.
그렇다고 자주 쓰이는 상품 도메인에 리뷰가 갱신될때마다 락을 걸면 여러 api들에 성능이 저하되겠죠.
요 부분은 상품에서 관리하기보다 별도 상품 리뷰 도메인을 만들어 관리하는게 좋아보이네요.
우선 중요한 부분은 아니니 나중에 천천히 수정해보세요

2024-05-08 15:39 UTC, f-lab-odee commented on src/main/java/com/mini/joymall/customer/domain/entity/Customer.java
> +    private long id;
현민님 id값은 null로 표현될 수 있는 값입니다.
재고 수량,가격 등은 빠르게 연산해야하고 null로 표현될 필요가 없으므로 박싱되지 않은 기본자료형을 써보는것을 추천드린건데요.
어떤 상황에서 기본 자료형을 쓰면 좋은지 이펙티브 자바 책이 있다면 item 61을 한번 읽어보세요

2024-05-09 11:23 UTC, pak0426 commented on src/main/java/com/mini/joymall/customer/domain/entity/Customer.java
> +    private long id;
이펙티브 자바 item 61에 대한 내용 읽고 블로그로 정리도 했는데 제대로 보고 수정을 했는데 replace를 하다보니까 그렇게 된거 같습니다..

Boxing된 타입 보다 기본 타입을 사용하면 좋은 점은
1. 참조 타입은 == 을 통한 비교를 하면 주소의 값이 다르기 때문에 결국 다르다라고 나옵니다.
2. NullPointException이 발생할 수 있습니다. Boxing된 타입을 초기화하지 않으면 에러가 발생합니다.
3. 시간과 메모리 사용면에서 더 효율적입니다. Boxing된 타입을 UnBoxing 하는데 시간이 소요되기 때문입니다.

멘토님 말씀대로 id는 null이 될 수 있으므로 Long으로 사용해야 합니다.

수정하겠습니다..!!

2024-05-17 07:01 UTC, merged